---

sudo: required
language: minimal
services:
  - docker


###
### Install requirements
###
install:
  - retry() {
      for ((n=0; n<50; n++)); do
        echo "[${n}] ${*}";
        if eval "${*}"; then
          return 0;
        fi;
      done;
      return 1;
    }


###
### Build Docker image
###
before_script:
  - retry make build
  - retry make test


###
### Push Docker image
###
script:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      make login USER="${DOCKERHUB_USERNAME}"  PASS="${DOCKERHUB_PASSWORD}";
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        make push;
      elif [ -n "${TRAVIS_TAG}" ]; then
        make tag NEW_TAG="${TRAVIS_TAG}";
        make push TAG="${TRAVIS_TAG}";
      elif [[ ${TRAVIS_BRANCH} =~ ^(OPS-[0-9]+)$ ]]; then
        make tag NEW_TAG="${TRAVIS_BRANCH}";
        make push TAG="${TRAVIS_BRANCH}";
      else
        echo "Builds resulting from normal branches are not pushed to Docker Hub.";
      fi
    else
      echo "Builds resulting from PRs are not pushed to Docker Hub.";
    fi
